version: 3
stages:
- 测试阶段
默认测试任务:
  label: develop
  stage: 测试阶段
  job_type: test
  only:
    branches:
    - .*
    tags:
    - .*
  before_script:
  - ""
  image: python:2.7
  install:
  - git clone -b master https://github.com/xiongzhun/sign_youqu.git
  - cd sign_youqu
  - pip install -r requirements.txt
  script:
  - python sign_youqu_tmp.py sign_all
  - python sign_youqu_tmp.py chat_all
  - python sign_youqu_tmp.py comment_all