version: 3
stages:
- 测试阶段
- 构建阶段
默认构建任务:
  label: release-image
  stage: 构建阶段
  job_type: image_build
  only:
    branches:
    - .*
    tags:
    - .*
  build_dir: /
  cache: true
  dockerfile_path: /Dockerfile
默认测试任务:
  label: develop
  stage: 测试阶段
  job_type: test
  only:
    branches:
    - .*
    tags:
    - .*
  before_script:
  - ""
  image: ubuntu:16.04
  install:
  - python sign_youqu_tmp.py chat_all
  - python sign_youqu_tmp.py comment_all
  - python sign_youqu_tmp.py sign_all
  script:
  - python sign_youqu_tmp.py chat_all
  - python sign_youqu_tmp.py comment_all
  - python sign_youqu_tmp.py sign_all